credentials:
  usernames:
    vesj:
      email: valteresj2@gmail.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Valter Eduardo
      password: D31m03@va # Will be hashed automatically
    brunorodas:
      email: brunorodas@gmail.com
      id: # Will be generated automatically
      logged_in: False # Will be managed automatically
      name: Bruno Rafael
      password: bruno@rodas # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com